name: Python Package

on:
  push:
    paths-ignore:
      - '**/README.md'
      - '.readthedocs.yml'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ['3.9']
        os: [windows-latest, ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies
      run: |
        poetry install --with dev

    - name: Run tests
      run: poetry run pytest

    - name: Run notebooks [Ubuntu only]
      if: runner.os == 'Linux'
      run: |
        cd notebooks
        find . -maxdepth 1 -name '*.ipynb' -print0 |
        xargs -0 -I {} jupyter nbconvert --execute --to notebook --inplace "{}"


    - name: Build and test documentation [Ubuntu only]
      if: runner.os == 'Linux'
      run: |
        cd docs
        poetry run make html
