name: Python Package

on:
  push:
    paths-ignore:
      - '**/README.md'
      - '.readthedocs.yml'
  pull_request:
    paths-ignore:
      - '**/README.md'
      - '.readthedocs.yml'
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ['3.9']
        os: [windows-latest, ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry pytest-cov
        poetry install --with dev -vvv

    - name: Run tests
      run: |
        poetry run pytest -vv
        pytest --cov-branch --cov-report=xml
        
    - name: Run notebooks [Ubuntu]
      if: runner.os == 'Linux'
      run: |
        pip install jupyterlab
        pip install -e .
        cd notebooks
        jupyter nbconvert --execute --to notebook get_started.ipynb

    - name: Build docs [Ubuntu]
      if: runner.os == 'Linux'
      run: |
        cd docs
        poetry run make html

    - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
